// St Tropez ES — product dataset (scraped from sttropeztan.com/uk via Apify)
// Prices: GBP RRP (provisional) -> EUR at rate 1.16. Edit `gbp` or set `eur` directly.
const RATE = 1.16;
const IMG = "https://sttropeztan.com/wp-content/uploads/";

const CATS = [
  { id: "espumas",     es: "Espumas autobronceadoras",        term: "espuma autobronceadora" },
  { id: "sprays",      es: "Brumas y sprays",                 term: "autobronceador en spray" },
  { id: "gradual",     es: "Autobronceador gradual",          term: "loción autobronceadora gradual" },
  { id: "instantaneo", es: "Bronceador instantáneo",          term: "bronceador instantáneo" },
  { id: "cuidado",     es: "Preparación y cuidado",           term: "cuidado del bronceado" },
  { id: "accesorios",  es: "Accesorios",                      term: "guante autobronceador" },
  { id: "kits",        es: "Kits y packs",                    term: "kit autobronceador" },
  { id: "profesional", es: "Profesional / Cabina",            term: "autobronceador profesional cabina" }
];

const PRODUCTS = [
  { slug:"espuma-classic-240ml", en:"Self Tan Classic Bronzing Mousse 240ml", es:"Espuma Autobronceadora Classic 240 ml", cat:"espumas", vol:"240 ml", gbp:35.80,
    img:IMG+"2023/07/Classic-30th-FOP-WB-Shadow.jpg",
    desc:"La icónica espuma autobronceadora St.Tropez para un bronceado dorado natural y fiable. De fácil aplicación con un toque de color guía, se desarrolla en 4-8 horas. Ideal tanto para principiantes como para un resultado perfecto siempre.",
    kw:["espuma autobronceadora","autobronceador corporal","fake tan","mousse bronceadora"] },
  { slug:"espuma-classic-120ml", en:"Self Tan Classic Bronzing Mousse 120ml", es:"Espuma Autobronceadora Classic 120 ml", cat:"espumas", vol:"120 ml", gbp:23.00,
    img:IMG+"2023/07/St.Tropez-Classic-Bronzing-Mousse-120ml.jpg",
    desc:"El formato de viaje de la espuma autobronceadora Classic más vendida. Bronceado dorado natural, uniforme y de larga duración, fácil de aplicar con guante.",
    kw:["espuma autobronceadora","autobronceador viaje","mousse bronceadora"] },
  { slug:"espuma-express-200ml", en:"Self Tan Express Bronzing Mousse 200ml", es:"Espuma Autobronceadora Express 200 ml", cat:"espumas", vol:"200 ml", gbp:40.00,
    img:IMG+"2023/07/Express-30th-FOP-WB-Shadow.jpg",
    desc:"Autobronceador exprés 3 en 1: elige la intensidad según el tiempo de pose (1, 2 o 3 horas). Color inmediato y un bronceado natural que controlas tú. Apto para todos.",
    kw:["autobronceador express","espuma autobronceadora rápida","fake tan 1 hora"] },
  { slug:"espuma-express-100ml", en:"Self Tan Express Bronzing Mousse 100ml", es:"Espuma Autobronceadora Express 100 ml", cat:"espumas", vol:"100 ml", gbp:23.00,
    img:IMG+"2023/07/St.Tropez-Self-Tan-Express-Bronzing-Mousse-100ml.jpg",
    desc:"El tamaño viaje del autobronceador exprés St.Tropez. Bronceado natural en tan solo 1 hora, de aplicación fácil y desarrollo controlado.",
    kw:["autobronceador express","espuma autobronceadora viaje"] },
  { slug:"espuma-dark-200ml", en:"Self Tan Dark Bronzing Mousse 200ml", es:"Espuma Autobronceadora Dark 200 ml", cat:"espumas", vol:"200 ml", gbp:35.00,
    img:IMG+"2023/07/St.Tropez-Self-Tan-Dark-Mousse-200ml.jpg",
    desc:"Nuestra icónica espuma autobronceadora oscura, con color guía más intenso para una aplicación sin zonas olvidadas. Desarrolla un bronceado profundo y natural adaptado a tu tono.",
    kw:["autobronceador oscuro","espuma autobronceadora dark","fake tan oscuro"] },
  { slug:"espuma-ultra-dark-violet-200ml", en:"Self Tan Ultra Dark Violet Bronzing Mousse 200ml", es:"Espuma Autobronceadora Ultra Dark Violet 200 ml", cat:"espumas", vol:"200 ml", gbp:37.00,
    img:IMG+"2024/02/St.Tropez-Self-Tan-Ultra-Dark-Violet-Bronzing-Mousse-200ml-Fake-Tan-NoReflection.jpg",
    desc:"Espuma autobronceadora ultra oscura con base violeta que neutraliza los tonos naranjas para un bronceado intenso, frío y sin reflejos anaranjados.",
    kw:["autobronceador ultra oscuro","base violeta","espuma autobronceadora intensa"] },
  { slug:"espuma-purity-200ml", en:"Self Tan Purity Bronzing Water Mousse 200ml", es:"Espuma Autobronceadora Purity (Agua) 200 ml", cat:"espumas", vol:"200 ml", gbp:25.20,
    img:IMG+"2023/07/St.Tropez-Self-Tan-Purity-Body-Mousse-200ml.jpg",
    desc:"Agua autobronceadora en espuma: sin aclarado, sin transferencia y sin olor a autobronceador. Fórmula limpia y vegana para un brillo dorado natural. Ideal para pieles claras.",
    kw:["agua autobronceadora","autobronceador vegano","espuma autobronceadora natural"] },
  { slug:"gel-purity-200ml", en:"Self Tan Purity Gel 200ml", es:"Gel Autobronceador Purity 200 ml", cat:"espumas", vol:"200 ml", gbp:25.00,
    img:IMG+"2023/07/St.Tropez-Self-Tan-Purity-Gel-200ml.jpg",
    desc:"Gel autobronceador transparente y ligero, de textura gel-agua, que desarrolla un bronceado medio natural en 3 horas. Hidratante y de rápida absorción.",
    kw:["gel autobronceador","autobronceador transparente","fake tan gel"] },
  { slug:"espuma-berry-sorbet-200ml", en:"Self Tan Berry Sorbet Bronzing Mousse 200ml", es:"Espuma Autobronceadora Berry Sorbet 200 ml", cat:"espumas", vol:"200 ml", gbp:35.00,
    img:IMG+"2023/07/St.Tropez-Tan-Berry-Sorbet-Mousse-200ml.jpg",
    desc:"Espuma autobronceadora con delicioso aroma a frutos rojos. Bronceado dorado natural de larga duración con color guía para una aplicación perfecta.",
    kw:["espuma autobronceadora","autobronceador aroma frutos rojos","fake tan"] },
  { slug:"espuma-express-dark-whipped-200ml", en:"Self Tan Express Dark Whipped Mousse 200ml", es:"Espuma Autobronceadora Express Dark Whipped 200 ml", cat:"espumas", vol:"200 ml", gbp:40.00,
    img:IMG+"2026/02/EXPRESS-DARK-MOUSSE-FOP-CAP-ON.jpg",
    desc:"Espuma batida exprés de acabado oscuro: textura aireada y ligera que se funde con la piel para un bronceado intenso y natural en tan solo 1-3 horas.",
    kw:["autobronceador express oscuro","espuma batida","fake tan oscuro rápido"] },
  { slug:"espuma-instant-glow-200ml", en:"Instant Glow Bronzing Mousse 200ml", es:"Espuma Autobronceadora Instant Glow 200 ml", cat:"espumas", vol:"200 ml", gbp:35.00,
    img:IMG+"2026/02/INSTANT-GLOW-MOUSSE-FOP-CAP-ON.jpg",
    desc:"Espuma autobronceadora con efecto luminosidad inmediata. Color guía radiante y un bronceado natural que se desarrolla de forma uniforme.",
    kw:["espuma autobronceadora","autobronceador luminoso","fake tan glow"] },
  { slug:"espuma-luxe-creme-200ml", en:"Luxe Tan Crème Mousse 200ml", es:"Espuma Crema Autobronceadora Luxe 200 ml", cat:"espumas", vol:"200 ml", gbp:35.00,
    img:IMG+"2023/07/St.Tropez-Luxe-Creme-Whipped-Mousse-200ml.jpg",
    desc:"Espuma crema autobronceadora de lujo, ultra hidratante, que cuida la piel mientras desarrolla un bronceado luminoso de dentro hacia fuera.",
    kw:["espuma crema autobronceadora","autobronceador hidratante","luxe tan"] },

  // SPRAYS / BRUMAS
  { slug:"bruma-express-mist-200ml", en:"Self Tan Express Bronzing Mist 200ml", es:"Bruma Autobronceadora en Spray Express 200 ml", cat:"sprays", vol:"200 ml", gbp:38.00,
    img:IMG+"2023/07/St.Tropez-Self-Tan-Express-Mist-200ml.jpg",
    desc:"Autobronceador en spray exprés de 1 hora. Aplicación 360º ideal para llegar a las zonas más difíciles. Bronceado natural y uniforme.",
    kw:["autobronceador en spray","bruma autobronceadora","self tan spray","autobronceador express spray"] },
  { slug:"bruma-purity-face-80ml", en:"Self Tan Purity Face Mist 80ml", es:"Bruma Autobronceadora Facial Purity 80 ml", cat:"sprays", vol:"80 ml", gbp:20.00,
    img:IMG+"2023/07/Purity-30th-FOP-WB-Shadow.jpg",
    desc:"Bruma autobronceadora facial hidratante que combina skincare y bronceado para un rostro luminoso y natural. Fórmula ligera tipo agua.",
    kw:["bruma autobronceadora facial","autobronceador cara","self tan facial spray"] },

  // GRADUAL
  { slug:"gradual-classic-lm", en:"Gradual Tan Classic Daily Firming Lotion Light/Medium", es:"Loción Autobronceadora Gradual Classic Claro/Medio", cat:"gradual", vol:"200 ml", gbp:22.00,
    img:IMG+"2023/07/Gradual-Tan-Classic-Daily-Firming-Lotion-Light-Medium.jpg",
    desc:"Loción hidratante reafirmante con autobronceador gradual. Construye un bronceado claro a medio día a día, con piel más firme e hidratada.",
    kw:["loción autobronceadora gradual","autobronceador progresivo","crema hidratante con bronceador"] },
  { slug:"gradual-classic-md", en:"Gradual Tan Classic Daily Firming Lotion Medium/Dark", es:"Loción Autobronceadora Gradual Classic Medio/Oscuro", cat:"gradual", vol:"200 ml", gbp:22.00,
    img:IMG+"2023/07/Gradual-Tan-Classic-Daily-Firming-Lotion-Medium-Dark.jpg",
    desc:"Loción hidratante reafirmante con autobronceador gradual para un bronceado medio a oscuro. Resultado progresivo y controlable, piel más firme.",
    kw:["loción autobronceadora gradual","autobronceador progresivo oscuro"] },
  { slug:"gradual-tinted", en:"Gradual Tan Tinted Daily Firming Lotion", es:"Loción Autobronceadora Gradual con Color", cat:"gradual", vol:"200 ml", gbp:22.00,
    img:IMG+"2023/07/Gradual-Tan-Tinted-Daily-Firming-Lotion.jpg",
    desc:"Loción autobronceadora gradual con color inmediato: aporta un toque de bronceado al instante mientras desarrolla un glow natural día a día.",
    kw:["loción autobronceadora con color","autobronceador gradual tintado"] },
  { slug:"gradual-watermelon", en:"Gradual Tan Watermelon Firming Lotion", es:"Loción Autobronceadora Gradual Sandía", cat:"gradual", vol:"200 ml", gbp:22.00,
    img:IMG+"2023/07/Gradual-Tan-Watermelon-Firming-Lotion.jpg",
    desc:"Loción autobronceadora gradual con aroma a sandía y activos reafirmantes. Hidrata y construye un bronceado natural de forma progresiva.",
    kw:["loción autobronceadora gradual","autobronceador sandía","crema bronceadora progresiva"] },

  // INSTANTÁNEO
  { slug:"instant-glow-body-bronzer-light", en:"Instant Glow Body Bronzer Light", es:"Bronceador Corporal Instantáneo Light", cat:"instantaneo", vol:"50 ml", gbp:25.00,
    img:IMG+"2023/07/St.Tropez-Instant-Glow-Body-Bronzer-%E2%80%93-Light.jpg",
    desc:"Maquillaje corporal bronceador de efecto inmediato y acabado natural que dura todo el día. Resistente al agua y a las manchas; se retira con agua y jabón. Tono claro.",
    kw:["bronceador instantáneo","maquillaje corporal bronceador","bronceador piernas"] },
  { slug:"instant-glow-body-bronzer-medium", en:"Instant Glow Body Bronzer Medium", es:"Bronceador Corporal Instantáneo Medium", cat:"instantaneo", vol:"50 ml", gbp:25.00,
    img:IMG+"2023/07/St.Tropez-Instant-Glow-Body-Bronzer-%E2%80%93-Light.jpg",
    desc:"Maquillaje corporal bronceador de efecto inmediato y acabado natural que dura todo el día. Resistente al agua y a las manchas; se retira con agua y jabón. Tono medio.",
    kw:["bronceador instantáneo","maquillaje corporal bronceador","bronceador piernas"] },
  { slug:"sunlit-skin-tint-tan-30ml", en:"Sunlit Skin Bronzing Tint + Tan 30ml", es:"Sunlit Skin Tinte Bronceador + Tan 30 ml", cat:"instantaneo", vol:"30 ml", gbp:25.00,
    img:IMG+"2025/05/0_SunlitSkin_Packshot_FOP_BottleCarton.jpg",
    desc:"Sérum 2 en 1 con color inmediato y autobronceador progresivo para el rostro. Aporta un acabado luminoso al instante que se transforma en bronceado natural.",
    kw:["tinte bronceador facial","sérum bronceador","autobronceador cara con color"] },

  // CUIDADO / PREPARACIÓN
  { slug:"luxe-body-serum-200ml", en:"Luxe Body Serum 200ml", es:"Sérum Corporal Luxe 200 ml", cat:"cuidado", vol:"200 ml", gbp:32.00,
    img:IMG+"2023/07/St.Tropez-Luxe-Body-Serum-200ml.jpg",
    desc:"Sérum corporal de lujo, hidratante y nutritivo, que prepara y cuida la piel para potenciar y prolongar el bronceado.",
    kw:["sérum corporal","hidratante corporal","cuidado del bronceado"] },
  { slug:"luxe-tonic-glow-drops-30ml", en:"Luxe Tan Tonic Glow Drops 30ml", es:"Gotas Bronceadoras Luxe Tan Tonic 30 ml", cat:"cuidado", vol:"30 ml", gbp:30.00,
    img:IMG+"2023/07/St.Tropez-Luxe-Tan-Tonic-Glow-Drops.jpg",
    desc:"Gotas autobronceadoras personalizables: añádelas a tu crema o sérum para crear el nivel de glow que quieras. Acabado luminoso a medida.",
    kw:["gotas autobronceadoras","drops bronceadores","autobronceador personalizable"] },
  { slug:"tan-optimiser-200ml", en:"Tan Optimiser Body Moisturiser 200ml", es:"Hidratante Prolongador del Bronceado 200 ml", cat:"cuidado", vol:"200 ml", gbp:22.00,
    img:IMG+"2023/07/St.Tropez-Tan-Optimiser-Body-Moisturiser-200ml.jpg",
    desc:"Hidratante corporal que prolonga la duración del bronceado y lo mantiene uniforme. Imprescindible para el cuidado posterior, apto para todo tipo de bronceado.",
    kw:["prolongador del bronceado","hidratante after tan","cuidado del bronceado"] },
  { slug:"body-polish-200ml", en:"Tan Body Polish and Exfoliator 200ml", es:"Exfoliante Corporal Preparador 200 ml", cat:"cuidado", vol:"200 ml", gbp:18.00,
    img:IMG+"2023/07/St.Tropez-Tan-Body-Polish-and-Exfoliator-200ml.jpg",
    desc:"Exfoliante corporal que prepara la piel para un autobronceado impecable, eliminando células muertas para un acabado uniforme y duradero.",
    kw:["exfoliante corporal","preparar piel autobronceado","scrub corporal"] },
  { slug:"tan-remover-mousse-200ml", en:"Tan Remover Mousse 200ml", es:"Mousse Eliminadora de Autobronceador 200 ml", cat:"cuidado", vol:"200 ml", gbp:18.00,
    img:IMG+"2023/07/St.Tropez-Tan-Remover-Mousse-200ml.jpg",
    desc:"Mousse que elimina de forma rápida y fácil los restos de autobronceador y prepara la piel para una nueva aplicación perfecta.",
    kw:["eliminador de autobronceador","quitar autobronceador","tan remover"] },

  // ACCESORIOS
  { slug:"mitt-dual-luxe", en:"Dual Sided Luxe Tanning Applicator Mitt", es:"Guante Aplicador Luxe Doble Cara", cat:"accesorios", vol:"1 ud.", gbp:8.00,
    img:IMG+"2023/07/St.Tropez-Dual-Sided-Luxe-Tanning-Applicator-Mitt.jpg",
    desc:"Guante aplicador de terciopelo de doble cara para un autobronceado sin estrías y manos sin manchas. El accesorio imprescindible.",
    kw:["guante autobronceador","aplicador autobronceador","mitt"] },
  { slug:"mitt-tan-remover", en:"Tan Remover Mitt", es:"Guante Exfoliante Eliminador", cat:"accesorios", vol:"1 ud.", gbp:9.00,
    img:IMG+"2023/07/St-Tropez-Tan-Remover-Mitt.jpg",
    desc:"Guante exfoliante que elimina los restos de autobronceador y la piel seca, dejando la piel lista para un bronceado perfecto.",
    kw:["guante exfoliante","eliminar autobronceador","guante quita bronceado"] },
  { slug:"face-brush", en:"Ultimate Tan Face Brush", es:"Brocha Facial Aplicadora", cat:"accesorios", vol:"1 ud.", gbp:18.00,
    img:IMG+"2025/05/0_FaceBrush_Packshot_CartonBrush.jpg",
    desc:"Brocha facial de precisión para aplicar el autobronceador en el rostro de forma uniforme y profesional, sin manchas en las manos.",
    kw:["brocha autobronceador facial","aplicador facial","brocha tan"] },

  // KITS
  { slug:"kit-award-winning", en:"Award-Winning Kit", es:"Kit Award-Winning (Premiado)", cat:"kits", vol:"Set", gbp:30.00,
    img:IMG+"2023/07/StTropez-Award-Winning-Kit.jpg",
    desc:"El set premiado con los esenciales St.Tropez para un bronceado perfecto. Una forma ideal de descubrir la gama autobronceadora.",
    kw:["kit autobronceador","set autobronceador","pack bronceado"] },
  { slug:"kit-express-starter", en:"Express Starter Kit", es:"Kit Express Starter", cat:"kits", vol:"Set", gbp:20.00,
    img:IMG+"2023/07/St.Tropez-Express-Starter-Kit.jpg",
    desc:"Kit de iniciación exprés: incluye la espuma autobronceadora Express y el guante aplicador de terciopelo. Glow en 1 hora.",
    kw:["kit autobronceador express","set iniciación bronceado"] },
  { slug:"kit-self-tan-classic", en:"Self Tan Classic Kit", es:"Kit Autobronceador Classic", cat:"kits", vol:"Set", gbp:22.00,
    img:IMG+"2023/07/St.Tropez-Self-Tan-Classic-Kit.jpg",
    desc:"El icónico kit Classic: espuma autobronceadora Classic tamaño viaje y guante aplicador Luxe. El dúo perfecto para empezar.",
    kw:["kit autobronceador classic","set espuma autobronceadora"] },
  { slug:"kit-purity-mini", en:"Self Tan Purity Mini Kit", es:"Mini Kit Autobronceador Purity", cat:"kits", vol:"Set", gbp:22.00,
    img:IMG+"2023/07/St.Tropez-Self-Tan-Purity-Mini-Kit.jpg",
    desc:"Mini kit Purity con aguas autobronceadoras de aroma tropical, guante aplicador y bruma facial Purity. Bronceado natural y limpio.",
    kw:["mini kit autobronceador","set purity","agua autobronceadora kit"] },
  { slug:"kit-berry-sorbet", en:"Self Tan Berry Sorbet Kit", es:"Kit Autobronceador Berry Sorbet", cat:"kits", vol:"Set", gbp:25.00,
    img:IMG+"2025/05/0_St.-Tropez-Tan-Self-Tan-Fake-Tan-Berry-Sorbet-Kit-No-Reflection.jpg",
    desc:"Kit Berry Sorbet con espuma autobronceadora de aroma a frutos rojos y guante aplicador. Bronceado dorado y delicioso.",
    kw:["kit autobronceador","set berry sorbet","pack espuma bronceadora"] },
  { slug:"kit-ultimate-body-essentials", en:"Ultimate Tan Body Essentials Kit", es:"Kit Ultimate Esenciales Corporales", cat:"kits", vol:"Set", gbp:45.00,
    img:IMG+"2026/02/Ultimate-Tan-Kit-Box-FOP-WITH-ALL-COMPONENTS.jpg",
    desc:"El kit completo con todos los esenciales para preparar, aplicar y prolongar el bronceado corporal perfecto. La gama St.Tropez en un solo pack.",
    kw:["kit completo autobronceador","set esenciales bronceado","pack autobronceador corporal"] },

  // PROFESIONAL
  { slug:"pro-classic-1l", en:"Professional Classic Bronzing Mist Spray Solution 1L", es:"Solución Profesional Classic Spray 1 L", cat:"profesional", vol:"1 L", gbp:40.00,
    img:IMG+"2025/05/0_St.Tropez-Classic-Bronzing-Mist-Spray-Solution-1L.jpg",
    desc:"Solución profesional Classic para bronceado en cabina con pistola/aerógrafo. Formato 1 litro para uso profesional. Resultado dorado natural.",
    kw:["autobronceador profesional cabina","solución spray tan 1L","bronceado profesional aerógrafo"] },
  { slug:"pro-express-1l", en:"Professional Express Bronzing Mist Spray Solution 1L", es:"Solución Profesional Express Spray 1 L", cat:"profesional", vol:"1 L", gbp:40.00,
    img:IMG+"2025/05/0_ExpressProfessional_Packshot.jpg",
    desc:"Solución profesional Express para bronceado en cabina de desarrollo rápido. Formato 1 litro para spray tan profesional.",
    kw:["autobronceador profesional express","spray tan cabina 1L","bronceado profesional rápido"] },
  { slug:"pro-ultra-dark-violet-1l", en:"Professional Ultra Dark Violet Mist Spray Solution 1L", es:"Solución Profesional Ultra Dark Violet Spray 1 L", cat:"profesional", vol:"1 L", gbp:40.00,
    img:IMG+"2025/05/0_SupremeViolet_Professional_Packshot.jpg",
    desc:"Solución profesional Ultra Dark Violet para cabina: base violeta que aporta un bronceado intenso y frío, sin reflejos anaranjados. Formato 1 litro.",
    kw:["autobronceador profesional oscuro","spray tan violeta cabina","bronceado profesional ultra dark"] }
];

if (typeof module !== "undefined") module.exports = { PRODUCTS, CATS, RATE, IMG };
